questions = [
    {'Q' : 'Lithium (Li) will react more violently with water than Natrium (Na)', 'A' : 'true'},
    {'Q': 'The higher the pH number of a solution, the higher its acidity', 'A': 'false'},
    {'Q': 'Structure of benzene was inspired from ouroboros', 'A': 'true'},
    {'Q': 'A balloon filled with oxygen will never be afloat to the sky', 'A': 'true'},
    {'Q': 'Graphite and diamond are made from the same element.', 'A': 'true'},
    {'Q': 'Carbon have two natural isotopes', 'A': 'false'},
    {'Q': 'Adding acid to water creates an exothermic reaction', 'A': 'false'},
    {'Q': 'Chemical compound polarized by earth magnetic field', 'A': 'false'},
    {'Q': 'Red phosphorus is more unstable than white phosphorus', 'A': 'false'},
    {'Q': 'Uranium is a lanthanoid', 'A': 'false'},
    {'Q': 'Chitin is the second most abundant organic molecule on earth.', 'A': 'true'},
    {'Q': 'Carbon and lead have different valence electron.', 'A': 'false'},
    {'Q': 'Precipitation can happens when a solution is supersaturated.', 'A': 'true'},
    {'Q': 'You can grow a crystal inside a solution by seeding.', 'A': 'true'},
    {'Q': 'Every matter in the universe are chemical', 'A': 'true'},
    {'Q': 'ATP is a compound consist of adenine, ribose, and two phospate group.', 'A': 'false'},
    {'Q': 'Once converted, ATP cannot be recycled back.', 'A': 'false'},
    {'Q': 'Lactic acid is a byproduct of anaerobic metabolism', 'A': 'true'},
    {'Q': 'DNA is the code molecule used by cells to creating proteins', 'A': 'false'},
    {'Q': 'In intracellular energy transfer, ATP can be converted twice when provides energy', 'A': 'true'},
    {'Q': 'The bread unique texture is caused by carbon dioxide created by yeast.', 'A': 'true'},
]